name: the-sweet-lab

services:
  postgres:
    image: postgres:16-alpine
    container_name: sweet_lab_postgres
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME:-the_sweet_lab_db}
      POSTGRES_USER: ${DB_USERNAME:-sweetlab_user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-sweetlab_password}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - sweet_lab_network

  redis:
    image: redis:7-alpine
    container_name: sweet_lab_redis
    restart: always
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis_data:/data
    networks:
      - sweet_lab_network

  mailpit:
    image: axllent/mailpit:latest
    container_name: sweet_lab_mailpit
    restart: always
    ports:
      - "${MAIL_PORT:-1025}:1025" # SMTP port
      - "8025:8025" # Web UI port to view received emails
    networks:
      - sweet_lab_network

volumes:
  postgres_data:
  redis_data:

networks:
  sweet_lab_network:
    driver: bridge
